BEGIN TRANSACTION;
CREATE TABLE `articles` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`title`	TEXT NOT NULL,
	`img`	TEXT,
	`pub_date`	TEXT NOT NULL,
	`body`	TEXT NOT NULL
);
INSERT INTO `articles` VALUES (1,'Nigeria center stage as ICDL Africa visits for the first time','http://icdlafrica.org/media/ng_trade_mission_frsc_event_301115.jpg','30.11.2015','The ICDL Africa team visited Nigeria in late November as part of an Irish Government Trade Mission. This was the first time that anyone from the team had visited Nigeria, the largest economy in Africa, with a population of over 170 million people.

The Trade Mission was organised by Enterprise Ireland, the Irish Government agency which supports Irish companies abroad. Given ICDL Foundation is headquartered in Ireland, it was a key opportunity for ICDL Africa to join over 30 other Irish companies in promoting business in Nigeria.

The highlight of the week for ICDL Africa was an event in which Minister for Agriculture, Food, the Marina and Defence, Simon Coveney visited the Federal Road Safety Corps headquarters in Abuja to present ICDL certificates to their staff. Enterprise Ireland CEO Julie Sinnamon and Irish Ambassador to Nigeria, H.E Séan Hoy were also in attendance. The Minister spoke highly of ICDL and the importance of skills development in the workforce. He was very impressed by the achievements of the FRSC and their commitment to digital skills, where over 2000 staff having been training and testing in the ICDL programme to date. The FRSC Corps Marshal Boboye Oyeyemi was very happy to receive the delegation and expressed his desire to expand the ICDL programme within the organisation.

In summarising the trip, ICDL Africa General Manager Séamus McGinley noted that Nigeria will be a high priority for the ICDL Africa team in 2016. With a strong network of existing ATCs in both Abuja and Lagos, there are many opportunities for ICDL to grow, particularly in targeting students and those working in the public sector. The Trade Mission allowed ICDL Africa to meet with key stakeholders in the ICT sector and put ICDL on the agenda at a national level. With the support of our Accreditation Consultant and ATC network, ICDL will be able to make key strides in 2016 and looks forward to returning to the market to help achieve this.');
INSERT INTO `articles` VALUES (2,'CEO market visit - Kenya and Rwanda','http://icdlafrica.org/media/kenya_trip_photo.png','11.03.2016','ICDL Foundation CEO Damien O’Sullivan and ICDL Africa General Manager Séamus McGinley were in Kenya and Rwanda at the start of March. During the visit to Kenya, a five year agreement was signed between ICDL Africa and local partner, E-Quest Ltd, strengthening the commitment of ICDL Africa to the Kenyan market. Meetings were also held with various ATCs to discuss the enhancements to the ICDL programme which will be introduced later this year.

From Kenya the team travelled to Rwanda where meetings were held with the Ministry of Youth and ICT, ATCs and other potential partners. The meetings focused mainly on introducing the 2016 enhancements, but other important issues such as Quality Assurance, standardization of the ICDL programme and introduction of new programmes, such as Digital Citizen and Digital Citizen Plus.');
INSERT INTO `articles` VALUES (3,'Irish Embassy in Ethiopia joins ICDL Africa ATC network
','http://icdlafrica.org/media/embassy_of_ireland_photo.jpg','14.04.2016','The Embassy of Ireland has been established in Ethiopia since 1994 with responsibilities of strengthening links between Ethiopia and Ireland, and is also home to Irish Aid’s bilateral programme. The Embassy supports the poorest and vulnerable sections in the Ethiopian society and provides a consular service to Irish citizens, and a visa service to those wishing to travel to Ireland. The Embassy is managed by Hon. Ambassador Aidan O’ Hara, with 24 local and 4 expatriate staff.
Earlier this year the Embassy was accredited as an ICDL Accredited Test Center with the aim to develop and enhance the digital skills of all Embassy staff. The Embassy chose ICDL because it offers training and testing solutions that are flexible, it will help to close the digital skills gap among staff in the workplace and because it is an internationally recognised qualification. The Embassy puts a high value on personal development and ICDL is an important tool to achieve that and also to enhance the overall productivity of staff.
“I hope that this initiative can be followed by others. ICDL is an Irish company offering an excellent certification that meets the needs of many organisations, including our own. ICDL training and testing will motivate all of our personnel, myself included! It will enhance our professional standing and allow us to be even more efficient in our day-to-day work.” Hon. Ambassador Aidan O’ Hara.
‘ICDL Africa is delighted to welcome the Irish Embassy in Addis Ababa to its network. The Embassy becomes the first Embassy worldwide to become an ICDL Accredited Test Centre. With its headquarters in Dublin, Ireland, ICDL Foundation continues to set the standard in digital skills around the world. With more than 15 million candidates, having taken over 60 million certification tests in over 100 countries since the programme began, nearly 20 years ago in Ireland. The Irish connection has remained strong, with ICDL Africa in particular, collaborating with Irish Embassies across the continent to further the digital skills agenda. We welcome Hon. Amabassador O’Hara and his team to the ICDL Africa network and we look forward to the certification of Embassy staff to the international standard with ICDL’ Séamus McGinley, General Manager – ICDL Africa.');
COMMIT;
